# Generated by Django 5.2.5 on 2025-08-09 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dielectric', '0004_migrate_datasets_to_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjectPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='dielectric.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
