# Generated by Django 5.2.5 on 2025-08-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectactivity',
            options={'verbose_name': 'project activity', 'verbose_name_plural': 'project activities'},
        ),
    ]
