# Generated by Django 5.2.5 on 2025-08-09 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_projectactivity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('collaborator', 'Collaborator'), ('read', 'Read'), ('triage', 'Triage'), ('write', 'Write'), ('maintain', 'Maintain'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=16),
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('collaborator', 'Collaborator'), ('read', 'Read'), ('triage', 'Triage'), ('write', 'Write'), ('maintain', 'Maintain'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='people.project')),
            ],
            options={
                'verbose_name': 'project invitation',
                'verbose_name_plural': 'project invitations',
                'indexes': [models.Index(fields=['token'], name='idx_people_invitation_token'), models.Index(fields=['email', 'status'], name='idx_people_invitation_email'), models.Index(fields=['project', 'status'], name='idx_people_invitation_project')],
                'unique_together': {('project', 'email')},
            },
        ),
    ]
